### ISSUE TITLE
Move the developer forum to CNCF infrastructure

### ISSUE THREAD

**Issue by johananl** [metallb/metallb#972]
## General

As a part of moving MetalLB under the CNCF, we can get access to infrastructure for facilitating community meetings. This includes access to Zoom.

Moving to Zoom makes sense for the following reasons:

- Using CNCF infrastructure for community meetings makes more sense than using infrastructure belonging to a specific company.
- Meet doesn't seem to allow starting a meeting before an organizer is present. This is counterproductive for us.
- Zoom usually offers better call quality than Meet.

Besides moving to Zoom, we should reconsider the way we publish meeting times and meeting notes. Lastly, we probably want to start recording community meetings.

## TODO

- [ ] Check with CNCF what is required for getting Zoom access.
- [ ] Check if there is a well-defined way for CNCF projects to publish meeting calendars. If so - adopt it. If not, find an alternative to the current Kinvolk-owned Google Calendar.
- [ ] Schedule a recurring Zoom meeting for the fortnightly MetalLB developer meetings and publish it in the appropriate place (see above).
- [ ] Create a (hopefully automated) process for recording meetings and sharing the recordings publicly.
